### ISSUE TITLE
Gramine PAL API adaption

### ISSUE THREAD

**Issue by jiazhang0** [confidential-containers/enclave-cc#7] opened 2022-03-24 01:20 UTC

**Comment by bigdata-memory** [comment] 2022-03-30 20:34
For this adoption, I come up with the following steps to achieve it according to our talks.

1) Determine the core interfaces of PAL APIs @YangLiang3 @bigdata-memory @ying2liu 
2) Design the workflows associated with those core interfaces @YangLiang3 @bigdata-memory @ying2liu 
3) Define the requirements about Gamine-SGX changes @ying2liu @bigdata-memory 
4) Collect the feedbacks from Gramine community @ying2liu @bigdata-memory 
5) Identify the constraints, custom changes, risks for Gramine adoption @ying2liu @bigdata-memory 
6) Abstract and define some acceptable Gramine specific APIs for adoption @ying2liu @bigdata-memory 
7) Consider adding some extensive interfaces to PAL API design to accommodate special needs of Gramine  @YangLiang3 @bigdata-memory 
8) Present the consolidated solution in Gramine meetings to reach some agreements @ying2liu @bigdata-memory 
9) Implement a PoC to validate that the adoption workflows work as expected @ying2liu
10) Review and verify the PoC under the whole picture of enclave-CC @YangLiang3 @ying2liu @bigdata-memory 
11) Develop a production version of PoC and PR for community review @ying2liu @bigdata-memory 
12) Maintain this adoption along with the upgrading of Gramine-sgx and PAL APIs design. @ying2liu @liang @bigdata-memory

**Comment by hdxia** [comment] 2022-03-30 20:40
This looks good to me

**Comment by ying2liu** [comment] 2022-04-02 00:07
Vijay and I discussed about enclave-cc architecture and interfaces with gramine with @YangLiang3 @bigdata-memory.
Gramine doesn’t support multiple processes in one enclave.  We must use different enclaves for the services (image service etc.), which is different approach from the original design. We could use local attestation to ensure the integrity. This might add some performance overhead, but if the overhead is significant, we could add enclave multi-process support to gramine (it might take some time).

**Comment by hdxia** [comment] 2022-04-02 00:20
> 

good point Ying. I think this also depends on the design of enclave agent. I think we should make the enclave agent only one process. the "image service" and "attestation agent" in the enclave agent should be considered module, not process. at the end, the enclave agent is one process if we can.

**Comment by bigdata-memory** [comment] 2022-04-02 03:28
Regarding the idea of separated Gramine-sgx processes will add extra complexity, IMHO, it does not only introduce some performance overhead, but also consume much more precious SGX EPC resources (even with EDMM enabled, the Gramine-SGX runtime will be duplicated 4 times at least). Not to mention that the attack surface will been much enlarged.

**Comment by YangLiang3** [comment] 2022-04-02 08:23
About PAL API's summary, let's discuss more according to your requirements. 

![image](https://user-images.githubusercontent.com/37134635/161374210-770a04a5-cc6e-4131-b000-fe7cd3c2ebb6.png)

For more details, please refer to the following link:
https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/docs/pal_programming_guide.md
https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/libenclave/internal/runtime/pal/spec.md
https://github.com/inclavare-containers/inclavare-containers/blob/master/rune/libenclave/internal/runtime/pal/spec_v2.md

**Comment by jiazhang0** [comment] 2022-04-02 08:33
@hdxia @bigdata-memory I fully agree on your comments and actually making AA and image-rs as a single process is the initial idea of enclave-cc. The only problem here is how AA is implemented as lib crate to allow to be imported by enclave-agent. @jialez0 is the maintainer of AA. He has opened an issue to discuss this: https://github.com/confidential-containers/attestation-agent/issues/53

**Comment by vijaydhanraj** [comment] 2022-04-02 18:03
@YangLiang3 thanks for your time in discussing the requirements with @ying2liu and me and for providing the details on the PAL APIs.

Gramine currently doesn't support
1) Multiple processes within an enclave.
2) Creating an empty enclave and not running any application.
3) Using exec to reuse the same enclave to launch another application.

I don't think we can do anything about gap 1 for now but let us not make the perfect enemy of good. I suggest we proceed with having a single process within an enclave and adding libraries/modules to the enclave as needed and doing a PoC first. Then evaluate with respect to performance, scalability, and EPC memory usage. 

But we do have some ideas on how to resolve gaps 2 and 3 as mentioned above and integrate these APIs in Gramine. The implementation of these APIs could slightly vary for Gramine. Please see below, 
 
1) Pal_init() could create an enclave with a dummy application that will simply wait for the real application. (This can address issue 2 as mentioned above)
2) Pal_exec() could talk to the dummy application which would then `exec` the real application. (This can address issue 3 as mentioned above)
3) Pal_create_process could create a new enclave and launch the application.

The other 3 APIs (Pal_get_version, Pal_kill, and Pal_get_localreport), could be supported without much effort.

What do you think?

PS: This is just an initial thought based on our internal discussions and not a design approved by Gramine maintainers.

**Comment by bigdata-memory** [comment] 2022-04-02 18:44
From design perspective, IMHO, the semantic of `Pal_init` is `Do libos initialization according to the incoming attr parameters.`,  if the `a dummy application` can serve this purpose, it could be named as Gramine-SGX init. module to avoid any confusion. 
Regarding the `Pal_exec`, it is defined as `Execute the program corresponding to pid.`, so it would be invoked with `pid` obtained from `Pal_create_process`. I don't see the `exec` family of functions can accept the 'pid' as its argument because the new process image should have already been created by `Pal_create_process`  that's why it cannot be used to replace the so-called `a dummy application` process image. 
For `Pal_create_process could create a new enclave and launch the application`, I think it creates a totally different sandbox context to the previous invocation of `Pal_init`, not to mention, the EPC resource consumption, complexity and security concerns.

**Comment by ying2liu** [comment] 2022-04-03 00:18
@hdxia Thank you so much for your input. We will have further discussion with enclave-cc stakeholders to get better understanding about the requirement. At the same time, we also have to consider Gramine's limitation.

**Comment by ying2liu** [comment] 2022-04-03 00:54
I think the three APIs: Pal_init(), Pal_create_process() and Pal_exec() are defined based on Occlum with enclave multi-process support. Occlum could initialize enclave and create processes in the enclave, but for gramine, only single process is supported in enclave. Even though we could use the same API names, but their internals will be different from Occlum.

**Comment by bigdata-memory** [comment] 2022-04-13 05:45
@jiazhang0 @YangLiang3 I found that the some of `rune Sub Commands` can not be well supported; because the semantics of command `exec` allows asynchronously running multiple applications after command `create`. as we know the Gramine-sgx is only capable to run single process so far. please see the following combinations in detail for clarification.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Combination of   rune subcommands | The design   considerations of Gramine-sgx  adoption | Supplemental info.
-- | -- | --
create->exec               ->exec               ->exec | Not supported;   until Gramine can run multiple process concurrently inside the same Gramine   enclave instance | Async. exec
create->start               ->start               ->start | May supported if   the Gramine can handover the control to init component after the previous   process got terminated; this feature has not yet been implemented but it is   acceptable to Gr community | execSync()
run | supported | Just invoking   pal_exec() once after pal_init()
delete | May supported; as   the impl. of pal_destroy() can send SIGINT/SIGTERM to Gramine-sgx; as the Gr   already support handling such signals to stop running process inside enclave |  
kill | supported |  
attest | Partially   supported; because the SGX REPORT can only be available to retrieve after   application actively writes its user data to two pseudo files, i.e.   /dev/attestation/user_report_data & target_info; therefore, the timing of   invoking pal_get_local_report() is constrained by  the application-specific operations   associated with user report data and target info. | Suggest retrieving   SGX QUOTE instead if possible to avoid relying SGX target_info



</div>


</body>

</html>

**Comment by ying2liu** [comment] 2022-04-14 17:35
yesterday's slide

**Comment by ying2liu** [comment] 2022-04-14 17:48
![image](https://user-images.githubusercontent.com/36203970/163447312-a9c073b9-ac4c-4e46-a6e1-298546230401.png)

**Comment by bigdata-memory** [comment] 2022-04-15 04:39
### Backup Solution of Gramine-SGX adoption for RunE API Integration

**Pros:**
+ Fast transform of container image if already cached (accredit to @vahldiek)
+ No changes to Gramine-SGX
+ Asynchronized Execution supported
+ Workload got measured together

**Cons: (Due to lack of FS volume support in Gramine)**
- File system structure revealed for app container.
- Gramine-sgx may not be used for Agent Enclave.

![RuneGra](https://user-images.githubusercontent.com/10856796/163517857-a7577a2d-d799-4a52-ab65-13196ce668ae.svg)

**Comment by mythi** [comment] 2022-04-27 12:44
(I had completely missed this thread even if I'm watching this repo)

> Backup Solution of Gramine-SGX adoption for RunE API Integration

@bigdata-memory is this being discussed somewhere or is it just an idea you shared here and asking for feedback?

**Comment by dcmiddle** [comment] 2022-04-27 13:10
I also missed this thread until mythi pointed it out.
Note that the original design was to match the VM-based usage, wherein the workload is not measured.
Similarly the app enclave would not need to attest to an external relying party. The App Enclave was intended to have a simple process capable of loading in the actual container. The simple or stub process would be the workload from the perspective of local attestation, which is only required for getting the encrypted filesystem key.

**Comment by bigdata-memory** [comment] 2022-04-27 18:11
@mythi  This is a backup solution I mentioned in meeting, and yes, conceptually, it is basically an alternative way to achieve the similar goal, we may consider this to hedge the risks in which plan A doesn't work under some constraints or assumptions broken. but any feedbacks or suggestions are warmly welcome, thanks.

**Comment by bigdata-memory** [comment] 2022-04-27 18:14
By the way, the backup solution doesn't include the attestation flow yet, I can add it according to V4 API if desired, thanks.

**Comment by ying2liu** [comment] 2022-07-05 23:37
![f8c30a6a-7fb7-40af-a390-90539f407cf3](https://user-images.githubusercontent.com/36203970/177433930-a69ec27a-09ff-499e-8e3f-814586a64e1d.jpg)

**Comment by ariel-adam** [comment] 2022-10-11 13:04
@jiazhang0 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by mythi** [comment] 2022-11-17 14:12
> @jiazhang0 is this issue still relevant or can be closed?

@jiazhang0 I'd think we could close this for now and re-open later if any PAL API changes become relevant. Agree?

**Comment by dcmiddle** [comment] 2022-11-18 19:56
cc: @ying2liu @bigdata-memory

**Comment by bigdata-memory** [comment] 2022-11-19 18:55
sure, please close it, thanks.

**Comment by hairongchen** [comment] 2022-11-24 01:34
closed for now, will reopen if needed

**Closed** 2022-11-24 04:33 UTC
Labels: documentation, epic
